version: '3.1'

services:
  
  node:
    container_name: node
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/home/node/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=2222
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=azerty
      - REDIS_HOST=redis
  postgres:
    container_name: postgres
    image: postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: db
      PGDATA: /data/postgres
    restart: unless-stopped
   nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: html/DockerFile
    ports:
      - "3000:3000"

    restart: on-failure
  redis:
   container_name: redis
   image: redis

networks:
  sub_network_db:
  sub_network_node: