FROM node:13.3-alpine

WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
USER node

COPY package*.json ./

RUN npm install

COPY index.js /home/node/app/index.js

EXPOSE 2222

CMD ["npm","run","start"]
